linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused
    - bodyclose
    - gocritic
    - misspell
    - unconvert
    - staticcheck
    - gosimple
    - stylecheck
    - goimports
    - depguard
    - gofmt
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - revive
    - path: mock.*.go
      linters:
        - revive
  include:
    - EXC0011 # https://golangci-lint.run/usage/false-positives/#exc0011
    - EXC0012 # https://golangci-lint.run/usage/false-positives/#exc0012
