// Code generated by "stringer -type Action --linecomment"; DO NOT EDIT.

package processors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[insert-0]
	_ = x[update-1]
	_ = x[upsert-2]
	_ = x[delete-3]
}

const _Action_name = "insertupdateupsertdelete"

var _Action_index = [...]uint8{0, 6, 12, 18, 24}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
