name: consul-telemetry-checks

on:
  push:
    branches:
    - main
    - 'release/*.*.x'
  pull_request:

jobs:
  get-go-version:
    name: "Determine Go toolchain version"
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Determine Go version
        id: get-go-version
        # We use .go-version as our source of truth for current Go
        # version, because "goenv" can react to it automatically.
        run: |
          echo "Building with Go $(cat .go-version)"
          echo "go-version=$(cat .go-version)" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs:
      - get-go-version
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ needs.get-go-version.outputs.go-version }}
      - name: Deps
        run: |
          make deps
      - name: Test
        run: |
          make go/test

  golangci:
    name: lint
    needs:
      - get-go-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ needs.get-go-version.outputs.go-version }}
      - name: Deps
        run: |
          make deps
      - name: Lint
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          make go/lint

  e2e:
    if: github.repository == 'hashicorp/consul-telemetry-collector' && contains(github.event.pull_request.labels.*.name, 'e2e')
    needs:
      [test, golangci]
    uses: ./.github/workflows/e2e.yml
    secrets: inherit