name: "E2E tests"

on:
  workflow_dispatch:
  push:
    branches: [e2e]
  #  pull_request:
  #  types:
  #    - labeled



env:
  CONTEXT: "ctx"
  BRANCH: "release/1.2.x"

jobs:
  kubernetes:
    #if: github.event.label.name == 'e2e' || github.event.label.name == 'e2e/kubernetes'
    name: kubernetes
    runs-on: ubuntu-latest
    steps:
    - uses: benc-uk/workflow-dispatch@798e70c97009500150087d30d9f11c5444830385 # v1.2.2
      name: kubernetes
      with:
        workflow: cloud.yml
        repo: hashicorp/consul-k8s-workflows
        ref: main
        token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
        inputs: '{ "context":"${{ env.CONTEXT }}", "repository":"hashicorp/consul-k8s", "branch":"${{ env.BRANCH }}", "sha":"${{ github.sha }}", "token":"${{ secrets.ELEVATED_GITHUB_TOKEN }}" }'
