name: "E2E tests"

on:
  workflow_call:



env:
  CONTEXT: "ctx"
  BRANCH: "release/1.2.x"
  PKG_NAME: "consul-telemetry-collector"

jobs:
  kubernetes:
    name: kubernetes
    runs-on: ubuntu-latest
    if: github.repository_owner == 'hashicorp'
    steps:
    - uses: benc-uk/workflow-dispatch@798e70c97009500150087d30d9f11c5444830385 # v1.2.2
      name: kubernetes
      with:
        workflow: collector.yml
        repo: hashicorp/consul-k8s-workflows
        ref: k8s-collector-workflow
        token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
        inputs: '{ "context":"${{ env.CONTEXT }}", "repository":"hashicorp/consul-telemetry-collector", "branch":"${{ env.BRANCH }}", "sha":"release/1.2.x", "token":"${{ secrets.ELEVATED_GITHUB_TOKEN }}" }'
