name: "E2E tests"

on:
  workflow_call:



env:
  CONTEXT: "consul-telemetry-collector-pr"
  BRANCH: ${{ github.head_ref || github.ref_name }}
  PKG_NAME: "consul-telemetry-collector"
  SHA: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  kubernetes:
    name: kubernetes
    runs-on: ubuntu-latest
    if: github.repository_owner == 'hashicorp'
    steps:
    - uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc # v1.2.4
      name: kubernetes
      with:
        workflow: collector.yml
        repo: hashicorp/consul-k8s-workflows
        token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
        ref: main
        inputs: '{ "context":"${{ env.CONTEXT }}", "repository":"${{ github.repository }}", "branch":"${{ env.BRANCH }}", "sha":"${{ env.SHA }}", "token":"${{ secrets.ELEVATED_GITHUB_TOKEN }}" }'
